version: "3.0"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"

  postgres_db:
    container_name: postgres_db
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin